# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CoreClass": "00_core.ipynb",
         "TSDataFrame": "01_TSDataFrame.ipynb"}

modules = ["core.py",
           "TSDataFrame.py"]

doc_url = "https://alvaroof.github.io/nbdevtest/"

git_url = "https://github.com/alvaroof/nbdevtest/tree/master/"

def custom_doc_links(name): return None
