# AUTOGENERATED! DO NOT EDIT! File to edit: 01_TSDataFrame.ipynb (unless otherwise specified).

__all__ = ['TSDataFrame']

# Cell
class TSDataFrame():
    def __init__(self):
        print("Created")
        self.counter = 0

    def add_count(self):
        self.counter += 1